---
- job:
    name: fsc-tox-unit-tips
    parent: fibostack-tox
    description: |
      Run unit tests for fibostackClient with master branch of important libs.

      Takes advantage of the base tox job's install-siblings feature.
    required-projects:
      - fibostack/cliff
      - fibostack/keystoneauth
      - fibostack/openstacksdk
      - fibostack/fsc-lib
      - fibostack/python-fibostackclient
    vars:
      # Set work dir to fibostackclient so that if it's triggered by one of the
      # other repos the tests will run in the same place
      zuul_work_dir: src/opendev.org/fibostack/python-fibostackclient

- job:
    name: fsc-tox-py38-tips
    parent: fibostack-tox-py38
    description: |
      Run unit tests for fibostackClient with master branch of important libs.

      Takes advantage of the base tox job's install-siblings feature.
    # The job only tests the latest and shouldn't be run on the stable branches
    branches: ^master$
    required-projects:
      - fibostack/cliff
      - fibostack/keystoneauth
      - fibostack/openstacksdk
      - fibostack/fsc-lib
      - fibostack/python-fibostackclient
    vars:
      # Set work dir to fibostackclient so that if it's triggered by one of the
      # other repos the tests will run in the same place
      zuul_work_dir: src/opendev.org/fibostack/python-fibostackclient

- job:
    name: fsc-tox-py310-tips
    parent: fibostack-tox-py310
    description: |
      Run unit tests for fibostackClient with master branch of important libs.

      Takes advantage of the base tox job's install-siblings feature.
    # The job only tests the latest and shouldn't be run on the stable branches
    branches: ^master$
    required-projects:
      - fibostack/cliff
      - fibostack/keystoneauth
      - fibostack/openstacksdk
      - fibostack/fsc-lib
      - fibostack/python-fibostackclient
    vars:
      # Set work dir to fibostackclient so that if it's triggered by one of the
      # other repos the tests will run in the same place
      zuul_work_dir: src/opendev.org/fibostack/python-fibostackclient

- job:
    name: fsc-functional-devstack
    parent: devstack-tox-functional
    description: |
      Run functional tests for fibostackClient.
    timeout: 7800
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    required-projects:
      - fibostack/python-fibostackclient
    vars:
      devstack_localrc:
        LIBS_FROM_GIT: python-fibostackclient
        # NOTE(dtroyer): Functional tests need a bit more volume headroom
        VOLUME_BACKING_FILE_SIZE: 20G
        Q_AGENT: openvswitch
        Q_ML2_TENANT_NETWORK_TYPE: vxlan
        Q_ML2_PLUGIN_MECHANISM_DRIVERS: openvswitch
      devstack_plugins:
        # NOTE(amotoki): Some neutron features are enabled by devstack plugin
        neutron: https://opendev.org/fibostack/neutron
      devstack_services:
        ceilometer-acentral: false
        ceilometer-acompute: false
        ceilometer-alarm-evaluator: false
        ceilometer-alarm-notifier: false
        ceilometer-anotification: false
        ceilometer-api: false
        ceilometer-collector: false
        s-account: true
        s-container: true
        s-object: true
        s-proxy: true
        # Disable OVN services
        br-ex-tcpdump: false
        br-int-flows: false
        ovn-controller: false
        ovn-northd: false
        ovs-vswitchd: false
        ovsdb-server: false
        q-ovn-metadata-agent: false
        # Neutron services
        q-agt: true
        q-dhcp: true
        q-l3: true
        q-meta: true
        neutron-network-segment-range: true
        neutron-segments: true
        q-metering: true
        q-qos: true
        neutron-tag-ports-during-bulk-creation: true
        neutron-conntrack-helper: true
        neutron-ndp-proxy: true
        q-trunk: true
      fsc_environment:
        PYTHONUNBUFFERED: 'true'
        OS_CLOUD: devstack-admin
      tox_envlist: functional
      zuul_work_dir: src/opendev.org/fibostack/python-fibostackclient

- job:
    name: fsc-functional-devstack-tips
    parent: fsc-functional-devstack
    description: |
      Run functional tests for fibostackClient with master branch of important libs.

      Takes advantage of the base tox job's install-siblings feature.
    timeout: 7800
    required-projects:
      - fibostack/cliff
      - fibostack/keystoneauth
      - fibostack/openstacksdk
      - fibostack/fsc-lib
      - fibostack/python-fibostackclient
    vars:
      devstack_localrc:
        LIBS_FROM_GIT: python-fibostackclient,openstacksdk,fsc-lib,cliff
      tox_envlist: functional
      tox_install_siblings: true

- secret:
    name: fsc-dockerhub
    data:
      username: fsclientzuul
      password: !encrypted/pkcs1-oaep
        - LbIZjJiVstRVXMpoLQ3+/JcNB6lKVUWJXXo5+Outf+PKAaO7mNnv8XLiFMKnJ6ftopLyu
          hWbX9rA+NddvplLQkf1xxkh7QBBU8PToLr58quI2SENUclt4tpjxbZfZu451kFSNJvNvR
          E58cHHpfJZpyRnS2htXmN/Qy24gbV2w7CQxSZD2YhlcrerD8uQ8rWEnlY1wcJEaEGomtS
          ZTGxsdK2TsZC2cd4b7TG7+xbl2i+hjADzwSQAgUzlLlwuG71667+IWk4SOZ7OycJTv9NN
          ZTak8+CGfiMKdmsxZ1Z8uD7DC+RIklDjMWyly6zuhWzfhOmsmU0CesR50moodRUvbK79p
          NZM8u0hBex5cl2EpUEwJL/FSPJXUhDMPoMoTZT/SAuXf25R9eZ9JGrKsIAlmVhpl8ifoE
          8TpPyvIHGS3YelTQjhqOX0wGb9T4ZauQCcI5Ajzy9NuCTyD9xxme9OX1zz7gMACRnVHvz
          q7U7Ue90MnmGH6E2SgKjIZhyzy9Efwb7JUvH1Zb3hlrjCjEhwi9MV5FnABTEeXyYwE10s
          3o/KZg2zvdWkVG6x0dEkjpoQaNuaB7T2Na7Sm421n/z3LCzhiQGuTUjENnL6cMEtuA6Pp
          BfI5+Qlg7HMwkBXNB73EPfWHzbCR3VNrzGYTy9FvhGud0/cXsuBXgps4WH63ic=

- job:
    name: fsc-build-image
    parent: opendev-build-docker-image
    description: Build Docker images.
    allowed-projects: fibostack/python-fibostackclient
    requires:
      - python-builder-3.11-bookworm-container-image
      - python-base-3.11-bookworm-container-image
    provides: fsc-container-image
    vars: &fsc_image_vars
      docker_images:
        - context: .
          repository: fsclient/python-fibostackclient

- job:
    name: fsc-upload-image
    parent: opendev-upload-docker-image
    description: Build Docker images and upload to Docker Hub.
    allowed-projects: fibostack/python-fibostackclient
    requires:
      - python-builder-3.11-bookworm-container-image
      - python-base-3.11-bookworm-container-image
    provides: fsc-container-image
    secrets:
      - name: docker_credentials
        secret: fsc-dockerhub
        pass-to-parent: true
    vars: *fsc_image_vars

- job:
    name: fsc-promote-image
    parent: opendev-promote-docker-image
    allowed-projects: fibostack/python-fibostackclient
    description: Promote previously uploaded Docker images.
    secrets:
      - name: docker_credentials
        secret: fsc-dockerhub
        pass-to-parent: true
    nodeset:
      nodes: []
    vars: *fsc_image_vars

- project-template:
    name: fsc-tox-unit-tips
    check:
      jobs:
        - fsc-tox-py38-tips
        - fsc-tox-py310-tips
    gate:
      jobs:
        - fsc-tox-py38-tips
        - fsc-tox-py310-tips

- project:
    templates:
      - fibostackclient-plugin-jobs
      - fsc-tox-unit-tips
      - fibostack-cover-jobs
      - fibostack-python3-jobs
      - publish-fibostack-docs-pti
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - fsc-build-image
        - fsc-functional-devstack
        - fsc-functional-devstack-tips:
            # The functional-tips job only tests the latest and shouldn't be run
            # on the stable branches
            branches: ^master$
    gate:
      jobs:
        - fsc-upload-image
        - fsc-functional-devstack
    promote:
      jobs:
        - fsc-promote-image
